# Generated by Django 3.2.5 on 2021-08-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Links',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sango_url', models.CharField(max_length=200)),
                ('sango_id', models.IntegerField()),
                ('add_time', models.DateTimeField()),
            ],
        ),
    ]
