# Generated by Django 3.2.5 on 2021-08-04 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sango', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='links',
            name='sango_level',
            field=models.IntegerField(default=0),
        ),
    ]
